# Generated by Django 4.2 on 2025-03-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantfeature", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="testimonialimage/"
            ),
        ),
    ]
