# Generated by Django 4.2 on 2025-03-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantfeature", "0002_testimonial_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="description",
            field=models.CharField(max_length=300),
        ),
    ]
