# Generated by Django 4.2 on 2025-03-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantfeature", "0004_alter_product_price_alter_special_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("profession", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="chefimage/"),
                ),
            ],
        ),
    ]
