# Generated by Django 4.2 on 2025-04-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantfeature", "0005_chef"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
